---
title: "RandomForest"
author: '510055611'
date: "2023-04-02"
output: html_document
---

```{r}
#stock 21 and stock 7
```


```{r,message=FALSE}
library(randomForest)
library(readr)
library(dplyr)
library(ggplot2)
```


```{r}
# Read files function
read_csv_file <- function(file) {
  read_csv(file, col_types = cols())
}
```


```{r,message=FALSE}
data_clust = read_csv("/Users/cco/Desktop/sample select.csv")
colnames(data_clust) = c("index","Stocks", "liquidity","cluster")
stock_names = data_clust$Stocks
stock_names = c(stock_names, "stock_31.csv", "stock_32.csv","stock_77.csv","stock_108.csv","stock_41.csv")
stock_names
```

```{r}
Generate path
path <- "/Users/cco/Desktop/individual_book_train/"
files <- paste0(path, stock_names)

```


```{r,message=FALSE}
#Read all stocks
data_frames <- lapply(files, function(file) {
  cat("Reading file:", file, "\n")
  read_csv(file)
})
```


```{r}
# calculate WAP
for (i in 1:length(data_frames)) {
  
  stocki = data_frames[[i]]
  
  WAP = (stocki$bid_price1*stocki$ask_size1 + stocki$ask_price1 * stocki$bid_size1)/(stocki$bid_size1 + stocki$ask_size1)
  data_frames[[i]] = stocki %>%
    mutate(wap = WAP)
  
}
```

```{r}
# Compute the BidAskSpread for all the snapshots of stock

for (i in 1:length(data_frames)) {
  
  data_frames[[i]] <- data_frames[[i]] %>% mutate(BidAskSpread = ask_price1 / bid_price1 - 1)
  
  data_frames[[i]] <- data_frames[[i]] %>% mutate(time_bucket = ceiling(seconds_in_bucket / 30), num_order = bid_size1 + ask_size1 + bid_size2 + ask_size2)
  
}

```


```{r,message=FALSE}
#log return
set.seed(3888)
Logr_stocks = list()

for (i in 1:length(data_frames)) {


  Log_r <- list() 
  
  timeIDs = unique(data_frames[[i]][, 1])[[1]]
  train_timeIDs = sample(timeIDs, 100)
  # obtain the random 50 time_id for stock, and find log return for each time id.
  
  for (j in 1 : length(train_timeIDs)){
  
    sec <- data_frames[[i]] %>% filter(time_id == train_timeIDs[j]) %>% pull(seconds_in_bucket)
    price <- data_frames[[i]] %>% filter(time_id == train_timeIDs[j]) %>% pull(wap)
    log_r <- log(price[-1] / price[1:(length(price) - 1)])
    Log_r[[j]] <- data.frame(time = sec[-1], log_return = log_r)
    
  }
  
  Logr_stocks[[i]] = Log_r

}

```


```{r}
# 600/30 = 20 data points for each 10-min time bucket
#Length of Volatility should be 25

Volatility = list()

for (j in 1:length(data_frames)) {
  
  Log_r = Logr_stocks[[j]]

  vol <- list()
  
  comp_vol <- function(x) {
    return(sqrt(sum(x ^ 2)))
  }
  
  for (i in 1 : length(Log_r)) {
    Log_r[[i]] <- Log_r[[i]] %>% mutate(time_bucket = ceiling(time / 30))
    vol[[i]] <- aggregate(log_return ~ time_bucket, data = Log_r[[i]], FUN = comp_vol)
    colnames(vol[[i]]) <- c('time_bucket', 'volatility')
  }
  
  Volatility[[j]] = vol

}
```


```{r}
# plot for first time id 
ggplot(data = Volatility[[30]][[99]], aes(x = time_bucket, y = volatility)) + geom_line() + geom_point()
```

```{r}
set.seed(3888)

Logr_stocks_t = list()

for (i in 1:length(data_frames)) {


  Log_r_t <- list() 
  
  timeIDs = unique(data_frames[[i]][, 1])[[1]]
  train_timeIDs = sample(timeIDs, 100)
  
  remaining_timeIDs <- setdiff(timeIDs, train_timeIDs)
  test_timeIDs = sample(remaining_timeIDs, 100)
  # obtain the random 50 time_id for stock, and find log return for each time id.
  
  for (j in 1 : length(test_timeIDs)){
  
    sec <- data_frames[[i]] %>% filter(time_id == test_timeIDs[j]) %>% pull(seconds_in_bucket)
    price <- data_frames[[i]] %>% filter(time_id == test_timeIDs[j]) %>% pull(wap)
    log_r_t <- log(price[-1] / price[1:(length(price) - 1)])
    Log_r_t[[j]] <- data.frame(time = sec[-1], log_return = log_r_t)
    
  }
  
  Logr_stocks_t[[i]] = Log_r_t

}
```



```{r}
#Calculate the volatility
Volatility_t = list()

for (j in 1:length(data_frames)) {
  
  Log_r_t = Logr_stocks_t[[j]]

  vol <- list()
  
  comp_vol <- function(x) {
    return(sqrt(sum(x ^ 2)))
  }
  
  for (i in 1 : length(Log_r)) {
    Log_r_t[[i]] <- Log_r_t[[i]] %>% mutate(time_bucket = ceiling(time / 30))
    vol[[i]] <- aggregate(log_return ~ time_bucket, data = Log_r_t[[i]], FUN = comp_vol)
    colnames(vol[[i]]) <- c('time_bucket', 'volatility')
  }
  
  Volatility_t[[j]] = vol

}
```


```{r}
ggplot(data = Volatility_t[[30]][[100]], aes(x = time_bucket, y = volatility)) + geom_line() + geom_point()
```


```{r}
#split the data into training and test sets

set.seed(3888)

Train = list()
Test = list()

for (j in 1:length(data_frames)) {
  
  timeIDs = unique(data_frames[[j]][, 1])[[1]]
  train_timeIDs = sample(timeIDs, 100)
  remaining_timeIDs <- setdiff(timeIDs, train_timeIDs)
  test_timeIDs = sample(remaining_timeIDs, 100)
  
  vol = Volatility[[j]]
  
  train_set <-  data_frames[[j]] %>%
  filter(is.element(time_id, train_timeIDs))
  test_set <-  data_frames[[j]] %>%
  filter(is.element(time_id, test_timeIDs))

  
  Train[[j]] = train_set
  Test[[j]] = test_set
}
```


```{r}
set.seed(3888)
L_reg = list()

for (j in 1:length(data_frames)) {

  list.reg <- list()
  vol = Volatility[[j]]
  
  timeIDs = unique(data_frames[[j]][, 1])[[1]]
  train_timeIDs = sample(timeIDs, 100)
  
  for (i in 1 : length(train_timeIDs)) {
    len.train = length(Volatility[[j]][[i]]$volatility)
    stats.bucket <- data_frames[[j]] %>% 
      filter(time_id == train_timeIDs[i] & time_bucket != 0) %>% 
      dplyr::select(c(BidAskSpread, wap, num_order, time_bucket)) 
    
    # for each 30-sec time bucket, we compute the following statistics
    mean.price <- aggregate(wap ~ time_bucket, data = stats.bucket, FUN = mean)
    mean.order <- aggregate(num_order ~ time_bucket, data = stats.bucket, FUN = mean)
    mean.BAS <- aggregate(BidAskSpread ~ time_bucket, data = stats.bucket, FUN = mean)
    
    list.reg[[i]] <- data.frame(volatility = Volatility[[j]][[i]]$volatility[-1], 
                                price = mean.price$wap[1:(len.train - 1)],
                                order = mean.order$num_order[1:(len.train - 1)],
                                BidAskSpread = mean.BAS$BidAskSpread[1:(len.train - 1)])
  }
  
  L_reg[[j]] = list.reg

}
```



```{r}
set.seed(3888)

Model = list()

for (j in 1:length(data_frames)) {
  
  vol = Volatility[[j]]
  lg = L_reg[[j]]

  # Train the models
  models <- list()
  
  for (i in 1 : length(vol)) {
    models[[i]] <- randomForest(volatility ~ ., data = lg[[i]], ntree = 1000, importance = TRUE)
  }
  
  Model[[j]] = models

}

```


```{r}
set.seed(3888)

L_test = list()

for (j in 1:length(data_frames)) {

    list.reg.test <- list()
    vol = Volatility_t[[j]]
    
  timeIDs = unique(data_frames[[j]][, 1])[[1]]
  train_timeIDs = sample(timeIDs, 100)
    
  remaining_timeIDs <- setdiff(timeIDs, train_timeIDs)
  test_timeIDs = sample(remaining_timeIDs, 100)
  
  for (i in 1 : length(test_timeIDs)) {
    
    len.train = length(Volatility[[j]][[i]]$volatility)
    len.val = length(Volatility_t[[j]][[i]]$volatility)
    
    stats.bucket <- data_frames[[j]] %>% 
      filter(time_id == test_timeIDs[i] & time_bucket != 0) %>% 
      dplyr::select(c(BidAskSpread, wap, num_order, time_bucket))
    mean.price <- aggregate(wap ~ time_bucket, data = stats.bucket, FUN = mean)
    mean.order <- aggregate(num_order ~ time_bucket, data = stats.bucket, FUN = mean)
    mean.BAS <- aggregate(BidAskSpread ~ time_bucket, data = stats.bucket, FUN = mean)
    
    list.reg.test[[i]] <- 
      data.frame(volatility = Volatility_t[[j]][[i]]$volatility, 
                 #price = mean.price$wap[len.train:(len.train + len.val - 1)],
                 price = mean.price$wap[1:(len.val)],
                 #order = mean.order$num_order[len.train:(len.train + len.val - 1)],
                 order = mean.order$num_order[1:(len.val)],
                 #BidAskSpread = mean.BAS$BidAskSpread[len.train:(len.train + len.val - 1)])
                 BidAskSpread = mean.BAS$BidAskSpread[1:(len.val)])
  }
    
  L_test[[j]] = list.reg.test
}
```


```{r}
set.seed(3888)

Prediction = list()

for (j in 1:length(data_frames)) {
  vol = Volatility_t[[j]]
  pred <- list()
  
  for (i in 1 : length(vol)) {
    pred[[i]] <- predict(Model[[j]][[i]], newdata = L_test[[j]][[i]])
  }
  
  Prediction[[j]] = pred
}
```


```{r}
plot(Volatility_t[[1]][[2]]$time_bucket, Prediction[[1]][[2]], type = "l",col = "red", ylab = "Volatility", xlab = "Time bucket")
lines(Volatility_t[[1]][[2]]$time_bucket, Volatility_t[[1]][[2]]$volatility,type = "l", col = "blue")
legend("topright", 
       legend = c("Prediction volatility", "volatility"),
       col = c("red", "blue"), lty = 1)

```


```{r}
#Calculate evaluation values

MSE = vector("list", 30)
QLIKE = vector("list", 30)
R_square = vector("list", 30)

for (j in 1:length(data_frames)) {
  
  mse <- vector()
  qlike <- vector()
  rsq <- vector()
  vol = Volatility_t[[j]]

  for (i in 1 : length(vol)) {
    mse <- c(mse, mean((Volatility_t[[j]][[i]]$volatility - Prediction[[j]][[i]]) ^ 2))
    qlike <- c(qlike, mean(Volatility_t[[j]][[i]]$volatility / Prediction[[j]][[i]] - log(Volatility_t[[j]][[i]]$volatility / Prediction[[j]][[i]]) - 1))
    rsq <- c(rsq, cor(Volatility_t[[j]][[i]]$volatility, Prediction[[j]][[i]]) ^ 2)
    
  }
  
  qlike <- qlike[is.finite(qlike)]
  
    
  MSE[[j]] = mse
  QLIKE[[j]] = qlike
  R_square[[j]] = rsq
    
}
```


```{r}
#Seperate clusters
Cl1_MSE <- c(MSE[[1]],MSE[[2]],MSE[[3]],MSE[[4]],MSE[[5]])
Cl1_Qlike <- c(QLIKE[[1]],QLIKE[[2]],QLIKE[[3]],QLIKE[[4]],QLIKE[[5]])
Cl2_MSE <- c(MSE[[6]],MSE[[7]],MSE[[8]],MSE[[9]],MSE[[10]])
Cl2_Qlike <- c(QLIKE[[6]],QLIKE[[7]],QLIKE[[8]],QLIKE[[9]],QLIKE[[10]])
Cl3_MSE <- c(MSE[[11]],MSE[[12]],MSE[[13]],MSE[[14]],MSE[[15]])
Cl3_Qlike <- c(QLIKE[[11]],QLIKE[[12]],QLIKE[[13]],QLIKE[[14]],QLIKE[[15]])
Cl4_MSE <- c(MSE[[16]],MSE[[17]],MSE[[18]],MSE[[19]],MSE[[20]])
Cl4_Qlike <- c(QLIKE[[16]],QLIKE[[17]],QLIKE[[18]],QLIKE[[19]],QLIKE[[20]])
Cl5_MSE <- c(MSE[[21]],MSE[[22]],MSE[[23]],MSE[[24]],MSE[[25]])
Cl5_Qlike <- c(QLIKE[[21]],QLIKE[[22]],QLIKE[[23]],QLIKE[[24]],QLIKE[[25]])
Cl6_MSE <- c(MSE[[26]],MSE[[27]],MSE[[28]],MSE[[29]],MSE[[30]])
Cl6_Qlike <- c(QLIKE[[26]],QLIKE[[27]],QLIKE[[28]],QLIKE[[29]],QLIKE[[30]])
```

```{r}
Cl1_rsq <- c(R_square[[1]],R_square[[2]],R_square[[3]],R_square[[4]],R_square[[5]])
Cl2_rsq <- c(R_square[[6]],R_square[[7]],R_square[[8]],R_square[[9]],R_square[[10]])
Cl3_rsq <- c(R_square[[11]],R_square[[12]],R_square[[13]],R_square[[14]],R_square[[15]])
Cl4_rsq <- c(R_square[[16]],R_square[[17]],R_square[[18]],R_square[[19]],R_square[[20]])
Cl5_rsq <- c(R_square[[21]],R_square[[22]],R_square[[23]],R_square[[24]],R_square[[25]])
Cl6_rsq <- c(R_square[[26]],R_square[[27]],R_square[[28]],R_square[[29]],R_square[[30]])
```


```{r}
length(Cl4_Qlike) = 500
length(Cl5_Qlike) = 500
```


```{r,warning=FALSE}
boxplot(Cl2_MSE,horizontal = TRUE , main = "Random Forest MSE")
boxplot(Cl2_Qlike, horizontal = TRUE, main = "Random Forest QLIKE")
```


```{r}
plot(Cl1_MSE, type = 'l', ylab = "MSE", xlab = "Stocks")#ylim = c(0,3e-05)
#lines(Cl2_MSE, col = "red")
#lines(Cl3_MSE, col = "blue")
#lines(Cl4_MSE, col = "green")
#lines(Cl5_MSE, col = "orange")
#lines(Cl6_MSE, col = "pink")
```


```{r}
plot(Cl1_Qlike, type = 'l',ylim = c(0,8) ,ylab = "Qlike", xlab = "Stocks")
lines(Cl2_Qlike, col = "red")
lines(Cl3_Qlike, col = "blue")
lines(Cl4_Qlike, col = "green")
lines(Cl5_Qlike, col = "orange")
lines(Cl6_Qlike, col = "pink")
```

```{r}
boxplot(Cl1_MSE,Cl2_MSE,Cl3_MSE,Cl4_MSE,Cl5_MSE,Cl6_MSE,horizontal = TRUE , main = "Random Forest MSE", ylab = "Clusters",xlab = "MSE value", names=c("Cl 1", "Cl 2", "Cl 3", "Cl 4", "Cl 5", "Cl 6"))
```
